[package]
name = "xorcrypt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64="0.13.0"
rand="0.8.4"

[lib]
proc-macro=true